<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "https://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="https://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<title>TestNG Report</title>
<style type="text/css">table {margin-bottom:10px;border-collapse:collapse;empty-cells:show}th,td {border:1px solid #009;padding:.25em .5em}th {vertical-align:bottom}td {vertical-align:top}table a {font-weight:bold}.stripe td {background-color: #E6EBF9}.num {text-align:right}.passedodd td {background-color: #3F3}.passedeven td {background-color: #0A0}.skippedodd td {background-color: #DDD}.skippedeven td {background-color: #CCC}.failedodd td,.attn {background-color: #F33}.failedeven td,.stripe .attn {background-color: #D00}.stacktrace {white-space:pre;font-family:monospace}.totop {font-size:85%;text-align:center;border-bottom:2px solid #000}.invisible {display:none}</style>
</head>
<body>
<table>
<tr><th>Test</th><th># Passed</th><th># Skipped</th><th># Retried</th><th># Failed</th><th>Time (ms)</th><th>Included Groups</th><th>Excluded Groups</th></tr>
<tr><th colspan="8">Dog Shelter Food Estimator Service - Functional Test suite</th></tr>
<tr><td><a href="#t0">Positive test Cases</a></td><td class="num">4</td><td class="num">0</td><td class="num">0</td><td class="num">0</td><td class="num">46</td><td></td><td></td></tr>
<tr class="stripe"><td><a href="#t1">Edge test Cases</a></td><td class="num">7</td><td class="num">0</td><td class="num">0</td><td class="num">0</td><td class="num">16</td><td></td><td></td></tr>
<tr><td><a href="#t2">Error test Cases</a></td><td class="num">4</td><td class="num">0</td><td class="num">0</td><td class="num attn">4</td><td class="num">24</td><td></td><td></td></tr>
<tr class="stripe"><td><a href="#t3">Cases Not Covered in ACs</a></td><td class="num">0</td><td class="num">0</td><td class="num">0</td><td class="num attn">1</td><td class="num">5</td><td></td><td></td></tr>
<tr><th>Total</th><th class="num">15</th><th class="num">0</th><th class="num">0</th><th class="num attn">5</th><th class="num">91</th><th colspan="2"></th></tr>
</table>
<table id='summary'><thead><tr><th>Class</th><th>Method</th><th>Start</th><th>Time (ms)</th></tr></thead><tbody><tr><th colspan="4">Dog Shelter Food Estimator Service - Functional Test suite</th></tr></tbody><tbody id="t0"><tr><th colspan="4">Positive test Cases &#8212; passed</th></tr><tr class="passedeven"><td rowspan="4">foodEstimatorServiceTests.positiveTestCases</td><td><a href="#m0">exampleCase</a></td><td rowspan="1">1629832658195</td><td rowspan="1">6</td></tr><tr class="passedeven"><td><a href="#m1">last_month_remaining_as_decimal</a></td><td rowspan="1">1629832658203</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m2">last_month_remaining_is_zero</a></td><td rowspan="1">1629832658205</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m3">total_number_of_dogs_equal_to_30</a></td><td rowspan="1">1629832658207</td><td rowspan="1">1</td></tr></tbody>
<tbody id="t1"><tr><th colspan="4">Edge test Cases &#8212; passed</th></tr><tr class="passedeven"><td rowspan="7">foodEstimatorServiceTests.edgeCases</td><td><a href="#m4">all_nums_zero</a></td><td rowspan="1">1629832658247</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m5">num_large_dogs_is_max</a></td><td rowspan="1">1629832658249</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m6">num_large_dogs_is_zero</a></td><td rowspan="1">1629832658251</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m7">num_med_dogs_is_max</a></td><td rowspan="1">1629832658253</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m8">num_med_dogs_is_zero</a></td><td rowspan="1">1629832658256</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m9">num_small_dogs_is_max</a></td><td rowspan="1">1629832658259</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m10">num_small_dogs_is_zero</a></td><td rowspan="1">1629832658261</td><td rowspan="1">1</td></tr></tbody>
<tbody id="t2"><tr><th colspan="4">Error test Cases &#8212; failed</th></tr><tr class="failedeven"><td rowspan="4">foodEstimatorServiceTests.errorCases</td><td><a href="#m11">num_large_dogs_is_negative</a></td><td rowspan="1">1629832658268</td><td rowspan="1">1</td></tr><tr class="failedeven"><td><a href="#m12">num_last_month_remaining_is_negative</a></td><td rowspan="1">1629832658273</td><td rowspan="1">1</td></tr><tr class="failedeven"><td><a href="#m13">num_med_dogs_is_negative</a></td><td rowspan="1">1629832658276</td><td rowspan="1">1</td></tr><tr class="failedeven"><td><a href="#m14">num_small_dogs_is_negative</a></td><td rowspan="1">1629832658279</td><td rowspan="1">1</td></tr><tr><th colspan="4">Error test Cases &#8212; passed</th></tr><tr class="passedeven"><td rowspan="4">foodEstimatorServiceTests.errorCases</td><td><a href="#m15">number_of_large_dogs_exceeds_max</a></td><td rowspan="1">1629832658282</td><td rowspan="1">0</td></tr><tr class="passedeven"><td><a href="#m16">number_of_med_dogs_exceeds_max</a></td><td rowspan="1">1629832658284</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m17">number_of_small_dogs_exceeds_max</a></td><td rowspan="1">1629832658286</td><td rowspan="1">1</td></tr><tr class="passedeven"><td><a href="#m18">total_number_of_dogs_exceeds_max</a></td><td rowspan="1">1629832658288</td><td rowspan="1">1</td></tr></tbody>
<tbody id="t3"><tr><th colspan="4">Cases Not Covered in ACs &#8212; failed</th></tr><tr class="failedeven"><td rowspan="1">foodEstimatorServiceTests.casesNotCoveredInACs</td><td><a href="#m19">last_month_remaining_is_more_than_needed</a></td><td rowspan="1">1629832658314</td><td rowspan="1">1</td></tr></tbody>
</table>
<h2>Positive test Cases</h2><h3 id="m0">foodEstimatorServiceTests.positiveTestCases#exampleCase</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m1">foodEstimatorServiceTests.positiveTestCases#last_month_remaining_as_decimal</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m2">foodEstimatorServiceTests.positiveTestCases#last_month_remaining_is_zero</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m3">foodEstimatorServiceTests.positiveTestCases#total_number_of_dogs_equal_to_30</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h2>Edge test Cases</h2><h3 id="m4">foodEstimatorServiceTests.edgeCases#all_nums_zero</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m5">foodEstimatorServiceTests.edgeCases#num_large_dogs_is_max</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m6">foodEstimatorServiceTests.edgeCases#num_large_dogs_is_zero</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m7">foodEstimatorServiceTests.edgeCases#num_med_dogs_is_max</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m8">foodEstimatorServiceTests.edgeCases#num_med_dogs_is_zero</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m9">foodEstimatorServiceTests.edgeCases#num_small_dogs_is_max</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m10">foodEstimatorServiceTests.edgeCases#num_small_dogs_is_zero</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h2>Error test Cases</h2><h3 id="m11">foodEstimatorServiceTests.errorCases#num_large_dogs_is_negative</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">org.testng.TestException: 
Method errorCases.num_large_dogs_is_negative()[pri:0, instance:foodEstimatorServiceTests.errorCases@42f93a98] should have thrown an exception of type class java.lang.Exception
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
	at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m12">foodEstimatorServiceTests.errorCases#num_last_month_remaining_is_negative</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">org.testng.TestException: 
Method errorCases.num_last_month_remaining_is_negative()[pri:0, instance:foodEstimatorServiceTests.errorCases@42f93a98] should have thrown an exception of type class java.lang.Exception
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
	at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m13">foodEstimatorServiceTests.errorCases#num_med_dogs_is_negative</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">org.testng.TestException: 
Method errorCases.num_med_dogs_is_negative()[pri:0, instance:foodEstimatorServiceTests.errorCases@42f93a98] should have thrown an exception of type class java.lang.Exception
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
	at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m14">foodEstimatorServiceTests.errorCases#num_small_dogs_is_negative</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">org.testng.TestException: 
Method errorCases.num_small_dogs_is_negative()[pri:0, instance:foodEstimatorServiceTests.errorCases@42f93a98] should have thrown an exception of type class java.lang.Exception
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
	at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m15">foodEstimatorServiceTests.errorCases#number_of_large_dogs_exceeds_max</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m16">foodEstimatorServiceTests.errorCases#number_of_med_dogs_exceeds_max</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m17">foodEstimatorServiceTests.errorCases#number_of_small_dogs_exceeds_max</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m18">foodEstimatorServiceTests.errorCases#total_number_of_dogs_exceeds_max</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h2>Cases Not Covered in ACs</h2><h3 id="m19">foodEstimatorServiceTests.casesNotCoveredInACs#last_month_remaining_is_more_than_needed</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [0.0] but found [-8.4]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEquals(Assert.java:701)
	at org.testng.Assert.assertEquals(Assert.java:712)
	at foodEstimatorServiceTests.casesNotCoveredInACs.last_month_remaining_is_more_than_needed(casesNotCoveredInACs.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
</body>
</html>
